Symbol_list *new_symbol_list();
Scope_node *_new_scope_node();
Scope_node* _copy_scope_node();
Scope_list *new_scope_list();
void scope_list_push(Scope_node* node);
void scope_stack_init();
void scope_stack_push();
void scope_set_name(char* name);
void scope_stack_pop();
Id_list *new_id_list();
void id_push_back(char* name);
For_it_list *new_for_list();
void for_it_push(char* it);
void for_it_pop();
void symbol_push_back(char* name, char* type, char* kind, char* attr);
void symbols_push_back(char* type, char* kind, char* attr);
void symbol_int_push_back(char* name, char* type, char* kind, int attr);
void symbols_int_push_back(char* type, char* kind, int attr);
void symbol_double_push_back(char* name, char* type, char* kind, double attr);
void symbols_double_push_back(char* type, char* kind, double attr);
void global_push_back(char* name, char* type, char* kind, char* attr);
void print_symbol_list();
void dumpSymbol();
Array_list* new_array();
void array_push(int num);
void sort_array(char* place);
Func_node* new_func();
void func_set_name(char *name);
void func_set_type(char *name);
void func_push_attr(char* type);
int string_to_oct(char* input);
